### ISSUE TITLE
Not an issue but need help implementing it the right way 

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [rodion-m/dio_smart_retry#10]
retry package works great if there is an error on initial request it goes into retry mode and if its successful retry does not happen 

so I wanted to see what happens if server is down and midway turns on 

- I closed the server 
- retry package started retrying I set retry to 3
- when the attempt number was 1 I turned on the server but then It still kept retrying 

` 
  Future uploadImage(
      {required File file, required Function onProgressUpdate}) async {
    Response? response;

    var dio = Dio();

    dio.interceptors.addAll([
      ///For Logging
      PrettyDioLogger(
          requestHeader: true,
          requestBody: true,
          responseBody: true,
          responseHeader: false,
          error: true,
          compact: true,
          maxWidth: 90),

      ///For Retrying
      RetryInterceptor(
        retryEvaluator: (DioError error, int attempt) {
          print('---------Rety Intercept Start---------');
          print('inty');
          print(attempt);
          ScaffoldMessenger.of(context).clearSnackBars();
          timerSnackbar(
            backgroundColor: Colors.black,
            context: context,
            buttonLabel: '',
            contentText:
                "Error ${error.error} - Attempt ${attempt.toString()} of 3",
            // buttonPrefixWidget: Image.asset(
            //   'assets/undo.png',
            //   width: 17.0,
            //   height: 15.0,
            //   alignment: Alignment.topCenter,
            //   color: Colors.blue[100],
            // ),
            afterTimeExecute: () => print("Operation Execute."),
            second: 5,
          );

          print('dioError');
          print(error.error.toString());
          print('---------Rety Intercept End---------');
          return true;
        },
        dio: dio,
        logPrint: print, // specify log function (optional)
        retries: 3, // retry count (optional)
        retryDelays: const [
          // set delays between retries (optional)
          Duration(seconds: 10), // wait 10 sec before first retry
          Duration(seconds: 10), // wait 10 more sec before second retry
          Duration(seconds: 10), // wait 10 more sec before third retry
          ///You can use timer snackbar package and show time before sending attempt again
        ],
      )
    ]);
    String fileName = file.path.split('/').last;
    FormData formData = FormData.fromMap({
      "image": await MultipartFile.fromFile(file.path, filename: fileName),
    });

    response = await dio.post(
      "http://127.0.0.1:8000/uploadImage/",
      data: formData,
      onSendProgress: (v1, v2) {
        ///v2 is the total size of file
        ///v1 is the current progress
        /// example output  v1 value is 590007 v2 value is 630413
        print('v1 value is ${v1.toString()}');
        print('v2 value is ${v2.toString()}');

        onProgressUpdate(((v1 / v2) * 100).toStringAsFixed(2));
      },
      onReceiveProgress: (v1, v2) {
        print('v1 from recieveProgress $v1');
        print('v2 from recieveProgress $v2');
      },
      options: Options(
        followRedirects: false,
      ),
    );
    print(response.data);
    print(response.statusMessage);
    return await response.data;
  }`

At first I get web socket error then I get 'Cant finalise a finalised multipart'

Also I was testing cancel token and if token is cancel it still retry is there a way I cancel retry via a function

**Comment by rodion-m** [comment]
Hi @officialFlutterDeveloper ! Thank you for contributing. Sorry for late response. \
> Also I was testing cancel token and if token is cancel it still retry is there a way I cancel retry via a function
Thanks for reporting this. It was fixed in  version1.3.2.

> retry package works great if there is an error on initial request it goes into retry mode and if its successful retry does not happen
To handle this case perhaps we have to reset  request's stream or something similar. We have to research Dio deeper to find a solution. PR is welcomed.

**Comment by rodion-m** [comment]
Fixed with https://github.com/rodion-m/dio_smart_retry/commit/63a3bddae8b5a0581c35c4ae5e973996561d9100
See #15
