### ISSUE TITLE
RetryInterceptor changes responseType to json

### ISSUE THREAD

**Issue by danielcmm** [rodion-m/dio_smart_retry#12]
Hi!

I dont know if im doing something wrong, but if i set the responseType to ResponseType.plain and the RetryInterceptor is executed after a timeout, the interceptor seems to set the responseType to ResponseType.json.

Example:

``

    final dio = Dio(
      BaseOptions(
        baseUrl: rootUri,
        connectTimeout: 3000,
        receiveTimeout: 5000,
        headers: headers,
        responseType: ResponseType.plain,
      ),
    );

    dio.interceptors.add(
      RetryInterceptor(
        dio: dio,
        logPrint: log, // specify log function (optional)
        retryDelays: const [
          Duration(seconds: 3), // wait 1 sec before first retry
          Duration(seconds: 5), // wait 2 sec before second retry
          Duration(seconds: 10), // wait 3 sec before third retry
        ],
      ),
    );

    try {
      response = await dio.get(url);
    ...

If there is no timeout, everything works fine.

Any ideas?

Thanks!

**Comment by rodion-m** [comment]
Hi @danielcmm ! It's very strange behavior. I've merged #16. Please give it another try with current github source code.

**Comment by rodion-m** [comment]
Fixed with https://github.com/rodion-m/dio_smart_retry/commit/63a3bddae8b5a0581c35c4ae5e973996561d9100
