### ISSUE TITLE
[Feature] Override default retryable status codes list

### ISSUE THREAD

**Issue by adelarsq** [rodion-m/dio_smart_retry#14]
We use an API that returns no default HTTP Status Codes for a lot of cases.

There is no way to change the API, so would be nice to be able to override the default status codes that should retry.

Related: https://github.com/rodion-m/dio_smart_retry/issues/11

**Comment by rodion-m** [comment]
Hi @adelarsq ! Thank you for contributing. It's possible to override the default status codes - just make your own DefaultRetryEvaluator and pass your status codes there. \
Here is an example:
```dart
    dio.interceptors.add(
      RetryInterceptor(
        dio: dio,
        logPrint: print,
        retryEvaluator: DefaultRetryEvaluator({status400BadRequest}).evaluate,
      ),
    );

    await dio.get<dynamic>('https://mock.codes/400');
```
Feel free to reopen if this is not a solution you wanted.

**Comment by adelarsq** [comment]
@rodion-m Cool! Thanks! I will follow that way.
