### ISSUE TITLE
✔️ Publish a version for DioX (done)

### ISSUE THREAD

**Issue by josh-burton** [rodion-m/dio_smart_retry#20]
Would you consider forking the package or publishing a version compatible with DioX?

https://pub.dev/packages/diox

**Comment by rodion-m** [comment]
> Would you consider forking the package or publishing a version compatible with DioX?
> 
> https://pub.dev/packages/diox

Perhaps. But what is this package? And what are the differences from dio?

**Comment by Shreemanarjun** [comment]
#21 this will may help.

**Comment by rodion-m** [comment]
The package for DioX has been published as a [prerelease](https://pub.dev/packages/dio_smart_retry/versions/2.0.0-diox)! You can use it like this:
```yaml
dio_smart_retry: ^2.0.0-diox
```
Please check this out.

**Comment by iTEEECH** [comment]
@rodion-m  Diox has been archived.

 The developper got the accesses of the Dio repo and will maintain Dio in 5.0.0

**Comment by SebastianKlaiber** [comment]
@iTEEECH [PR](https://github.com/rodion-m/dio_smart_retry/pull/23) is created, maybe you could compare it with your PR and review my changes? Thanks.

**Comment by rodion-m** [comment]
The new version with dio 5.0.0 support is available as `dio_smart_retry: ^5.0.0`.
