### ISSUE TITLE
android issue

### ISSUE THREAD

**Issue by sharadgoregore** [rodion-m/dio_smart_retry#26]
not working for android

**Comment by Aruljebaraj** [comment]
Same here it doesn't work for Android

**Comment by rodion-m** [comment]
@sharadgoregore @Aruljebaraj Could you please provide error details?

**Comment by sharadgoregore** [comment]
I/ViewRootImpl@3ab62e4[MainActivity](18237): MSG_WINDOW_FOCUS_CHANGED 0 1


D/InsetsSourceConsumer(18237): ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.todo/com.todo.MainActivity


D/InsetsSourceConsumer(18237): ensureControlAlpha: for ITYPE_STATUS_BAR on com.todo/com.todo.MainActivity


I/ViewRootImpl@3ab62e4[MainActivity](18237): MSG_WINDOW_FOCUS_CHANGED 1 1


D/InputMethodManager(18237): startInputInner - Id : 0


I/InputMethodManager(18237): startInputInner - mService.startInputOrWindowGainedFocus

This is what i am getting after on click on wifi button to start internet but same code working while uploding photos in ios

**Comment by rodion-m** [comment]
@sharadgoregore Weird error. Does clean dio (without dio_smart_retry) work fine?

**Comment by sharadgoregore** [comment]
yes it works but i want to resume api function while uploading or downloading  photos.. if network disconnected and connected again it should resume api function this is working fine in ios but not working in android and  error also not in detailed so not able to understand what exactly issue is...please can you try from your end?so you may get more idea about that issue

**Comment by rodion-m** [comment]
I assume that our library cannot cause this error. SO says that this error about WiFi enabling/disabling: https://stackoverflow.com/questions/60040077/databinding-inputmethodmanager-startinputinner-mservice-startinputorwindowg

**Comment by sharadgoregore** [comment]
thanks for replying but i am getting this issue for both wifi and mobile internet on android only..i have tried on both virtual and physical device

**Comment by sharadgoregore** [comment]
yeah without this package dio works fine but in ios both package dio_smart_retry and dio works fine in android only facing issue..

**Comment by sharadgoregore** [comment]
hi @rodion-m any update??

**Comment by rodion-m** [comment]
hi, we've updated the program to 7.0, and the issues should be fixed. feel free to reopen it if it's not.
