### ISSUE TITLE
on retry callback 

### ISSUE THREAD

**Issue by zezo357** [rodion-m/dio_smart_retry#3]
if possible can an on retry callback is called with the status of the request

(using it to let user know that request failed and the code is retrying)

**Comment by zezo357** [comment]
made a pull request with it

**Comment by rodion-m** [comment]
Hey @zezo357 . Thank you for contributing! \
I'm afraid that adding another callback into `RetryInterceptor` just will make it more complex to use and don't bring us something new. \
You can catch a retry like this:
```dart
FutureOr<bool> myRetryEvaluator(DioError error, int attempt) {
  // here your retry interception logic
  return RetryInterceptor.defaultRetryEvaluator(error, attempt);
}
RetryInterceptor(..., retryEvaluator: myRetryEvaluator);
```
That's it.

**Comment by zezo357** [comment]
> Hey @zezo357 . Thank you for contributing! \
> I'm afraid that adding another callback into `RetryInterceptor` just will make it more complex to use and don't bring us something new. \
> You can catch a retry like this:
> ```dart
> FutureOr<bool> myRetryEvaluator(DioError error, int attempt) {
>   // here your retry interception logic
>   return RetryInterceptor.defaultRetryEvaluator(error, attempt);
> }
> 
> RetryInterceptor(..., retryEvaluator: myRetryEvaluator);
> ```
> That's it.

Oh okay thanks for the example


I think it would be better if it's in the documentation to make it easier for the other people too

**Comment by mathiasgodwin** [comment]
> 

Can someone pls show the full implementation of that? Thanks in advance

**Comment by zezo357** [comment]
from what i understood it can be done like that @mathiasgodwin 

i didnt test the code so i hope it has no errors
```
final dio = Dio();

FutureOr<bool> myRetryEvaluator(DioError error, int attempt) {
  // here your retry interception logic
  return RetryInterceptor.defaultRetryEvaluator(error, attempt);
}


// Add the interceptor
dio.interceptors.add(RetryInterceptor(
  dio: dio,
  retryEvaluator: myRetryEvaluator,
  logPrint: print, // specify log function (optional)
  retries: 3, // retry count (optional)
  retryDelays: const [ // set delays between retries (optional)
    Duration(seconds: 1), // wait 1 sec before first retry
    Duration(seconds: 2), // wait 2 sec before second retry
    Duration(seconds: 3), // wait 3 sec before third retry
  ],
));

/// Sending a failing request for 3 times with 1s, then 2s, then 3s interval
await dio.get('https://mock.codes/500');
```

**Comment by mathiasgodwin** [comment]
Thank you very much @zezo357 I look forward to implement it very soon.

**Comment by rodion-m** [comment]
I guess we've solved it. Feel free to open this issue if you get another thoughts about this topic.
