### ISSUE TITLE
How is no connectivity handled?

### ISSUE THREAD

**Issue by sunilguptasg** [rodion-m/dio_smart_retry#31]
If there is a network issue (no internet) how is this handled? Will this package retry when the network is back?

**Comment by burekas7** [comment]
+1

**Comment by rodion-m** [comment]
Requests falied with connection errors will be retried using `retryEvaluator`. You can add specific rules to you own retryEvaluator, like awaiting for a connection, but I think that it's better to solve connection errors in the highest level of you app. If you have something to add, feel free to reopen this.
