### ISSUE TITLE
How to know which API call is a retry and which is the original call

### ISSUE THREAD

**Issue by Basel-525k** [rodion-m/dio_smart_retry#34]
Hi, I'm trying to figure out how to know which of the API calls I made are retry calls and which are not

Use case:
- I have another interceptor that handles errors, the method has an action that only needs to be triggered once, I can see in the package code that there is an extension that adds the attempt index, can we have it public?

**Comment by Basel-525k** [comment]
I see that the "ro_attempt" was added to the extras so that we can achieve such a goal, unfortunately, it always returns the number of attempts rather than the index of the current one

**Comment by rodion-m** [comment]
Hi @Basel-525k ! I don't like the way to share a const. I think it's better just to make the attempt field public. Please check this out:  **https://github.com/rodion-m/dio_smart_retry/blob/637106a916e0a644b666848d0aaf2d5571408900/lib/src/retry_interceptor.dart#L224**

Feel free to reopen it if it doesn't meet your requirements.
