### ISSUE TITLE
Issue with onError handling on newer version of Dio

### ISSUE THREAD

**Issue by ryanaidilp** [rodion-m/dio_smart_retry#38]
Apparently there is an issue related to this https://github.com/cfug/dio/issues/2167

**Comment by AlexV525** [comment]
Could you provide more details? The interceptor that this library wrote does not implies `async` with `void`.

**Comment by ryanaidilp** [comment]
Seems like the issue is with dio itself and it's already fixed in the latest `2.4.5+1` version. I will close this issue. Thanks for your response.
