### ISSUE TITLE
FileSystemException: File closed

### ISSUE THREAD

**Issue by DmitryGaimaldinov** [rodion-m/dio_smart_retry#43]
Hello! We use this package in our commercial project and faced that this error is happening when using `MultipartFileRecreatable.fromFileSync()`. After some research I found out which causes this error and made a fix https://github.com/rodion-m/dio_smart_retry/pull/42

Upd: I also tested the code from this pull request in our project to convince that everything's working

**Comment by oantacamelia** [comment]
We are also facing the same error. Thanks for fixing i!

**Comment by rodion-m** [comment]
fixed with #42
