### ISSUE TITLE
Enable retry for specific request

### ISSUE THREAD

**Issue by HugoHeneault** [rodion-m/dio_smart_retry#6]
Hi there, 

Awesome pub! Thanks :)
I'd like to enable it only for one request! Is that possible?

Thanks

**Comment by rodion-m** [comment]
Hi @HugoHeneault ! Thank you for contributing.
No, it's not supported at the moment. But it's possible to disable retry manually for each request:
```dart
final request = RequestOptions(path: '/')..disableRetry = true;
```
What is the case? Perhaps we can consider an implementation of requested functionality.

**Comment by HugoHeneault** [comment]
I have an app transmitting GPS coordinates for security, and would like to retry on fail. 
But all other requests don't need retries.

**Comment by rodion-m** [comment]
If it's still relevant I can suggest to use an extra interceptor that will modify request options and explicitly set `disableRetry` option to true.

**Comment by rodion-m** [comment]
Another simple way is to add your own retry evaluator. Here is a full example:
``` dart
final dio = Dio();

FutureOr<bool> myRetryEvaluator(DioError error, int attempt) {
    if(error.requestOptions.extra['enableRetry'] == false) {
      return false;
    }
  return RetryInterceptor.defaultRetryEvaluator(error, attempt);
}

// Add the interceptor
dio.interceptors.add(RetryInterceptor(
  dio: dio,
  retryEvaluator: myRetryEvaluator,
));

await dio.get('https://mock.codes/500');
```
Now all requests by default will not be retried. \
You have to enable retries explicitly to enable retries for a specified request:
```dart
final request = RequestOptions(path: '/')
  ..extra['enableRetry'] = true;
await dio.fetch<String>(request);
```
