### ISSUE TITLE
disableRetry doesn't seem to work

### ISSUE THREAD

**Issue by chaser79** [rodion-m/dio_smart_retry#7]
Hello I have tried to use the disableRetry but it isn't working correctly.

This is my dio request
```dart
final requestOptions = RequestOptions(
      method: method,
      baseUrl: _dio.options.baseUrl,
      path: path,
      headers: headers,
      data: data,
      queryParameters: queryParameters,
      onSendProgress: onSendProgress,
      onReceiveProgress: onReceiveProgress,
      extra: {
        'Test': 'This is an extra test'
      },
    )..disableRetry = true;
return _dio.fetch(requestOptions);
```

I have looked into the problem and it looks as though the extra on the requestOptions is empty on the onError override of the interceptor.

```dart
@override
  Future onError(DioError err, ErrorInterceptorHandler handler) async {
    print(err.requestOptions.extra); //<--- this is always empty even when extra parameters are added.
}
```

Not sure if its a dio issue.

**Comment by rodion-m** [comment]
Hey @chaser79 . Thank you for contributing. \
I've written a test for `disableRetry ` and it works fine: https://github.com/rodion-m/dio_smart_retry/blob/master/test/retry_interceptor_tests.dart#L7 \
How did you get a wrong result? Could you please provide an example or event better contribute another test for your case?

**Comment by chaser79** [comment]
Hello, 

Thanks for your quick reply. After doing some more digging I noticed another interceptor that was resetting the requestOptions.extra list before the request was made. After fixing that interceptor everything worked as expected.

I will close this issue.
