### ISSUE TITLE
frequent infinite retries

### ISSUE THREAD

**Issue by CyJaySong** [rodion-m/dio_smart_retry#8]
Always unlimited retry, When the network is unstable。

**Comment by rodion-m** [comment]
Hey @CyJaySong . Could you please provide more info how to reproduce the bug?

**Comment by CyJaySong** [comment]
@rodion-m Thank you for your reply，when I turn off and turn on the network, I will have the opportunity to trigger it. It may take several minutes to repeat.

**Comment by rodion-m** [comment]
@CyJaySong I'll close this issue. If you reproduce it, feel free to reopen the issue with extra details.
